# Generated by Django 2.2.12 on 2020-05-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('question1', models.TextField(max_length=350)),
                ('question2', models.TextField(max_length=350)),
                ('question3', models.TextField(max_length=350)),
                ('question4', models.TextField(max_length=350)),
            ],
        ),
    ]
