# Generated by Django 2.2.12 on 2020-05-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
