# Generated by Django 2.2.12 on 2020-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
    ]
