# Generated by Django 2.2.12 on 2020-05-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200515_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.IntegerField(verbose_name=-10),
        ),
    ]
